name: claude

services:
  claude:
    build:
      context: .
    image: claude
    container_name: claude
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - ${HOST_CONTAINER_HOME_DIR}:${CONTAINER_HOME_DIR}
      - ${HOST_WORK_DIR}:${CONTAINER_WORK_DIR}
    stdin_open: true
    tty: true
    network_mode: "host"
    hostname: claude
    restart: unless-stopped
